###
POST http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json

{
    "name": "Roberto",
    "age": "44",
    "email":"robertoloveRM@email.com"
}

###

GET http://localhost:9000/api/user HTTP/1.1

###

GET http://localhost:9000/api/user/62b03cd33dd10f65af0b40a4 HTTP/1.1

###

PUT http://localhost:9000/api/user/62b03cd33dd10f65af0b40a4 HTTP/1.1
Content-Type: application/json

{
    "name": "Roberto ",
    "age": "24",
    "email":"roberto@email.com"
}

### 

DELETE  http://localhost:9000/api/users/62b03cd33dd10f65af0b40a4 HTTP/1.1












###

POST http://localhost:9000/api/categoria HTTP/1.1
Content-Type: application/json

{
    "name": "INDIE"
}

###

GET http://localhost:9000/api/categoria HTTP/1.1

###

GET http://localhost:9000/api/categoria/62b0525309eed51311b9084a HTTP/1.1

###
PUT http://localhost:9000/api/categoria/62b0525309eed51311b9084a HTTP/1.1
Content-Type: application/json

{
    "name": "POP moderno ",
}

###

DELETE  http://localhost:9000/api/categoria/62b0525309eed51311b9084a HTTP/1.1












###
POST http://localhost:9000/api/videos HTTP/1.1
Content-Type: application/json

{
    "name": "Video 3",
    "categoria": "FLAMENCO" ,
    "url": "https://www.youtube.com/watch?v=txGObix4GTk"
}

###

GET http://localhost:9000/api/videos HTTP/1.1

###

GET http://localhost:9000/api/videos/62b056d29cd6e7378962561c HTTP/1.1

###

PUT http://localhost:9000/api/videos/62b056d29cd6e7378962561c HTTP/1.1
Content-Type: application/json

{
    "name": "Video1.0 ",
    "URL":""
}

### 

DELETE  http://localhost:9000/api/videos/62b056d29cd6e7378962561c HTTP/1.1
